services:
  - type: web
    name: yeloo-api
    env: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_ORIGIN
        sync: false
      - key: FRONTEND_ORIGINS
        sync: false
      - key: BOOTSTRAP_ADMIN_EMAIL
        value: admin@yeloo.ci
      - key: BOOTSTRAP_ADMIN_PASSWORD
        sync: false
      - key: BOOTSTRAP_ADMIN_FULL_NAME
        value: Super Admin Yeloo
      - key: MINIO_ENDPOINT
        sync: false
      - key: MINIO_ACCESS_KEY
        sync: false
      - key: MINIO_SECRET_KEY
        sync: false
      - key: MINIO_BUCKET
        value: yeloo-media
      - key: MINIO_SECURE
        value: true
      - key: MINIO_PUBLIC_URL
        sync: false
      - key: MINIO_PUBLIC_URL_IS_BUCKET_ROOT
        value: true
