import uuid
from datetime import datetime

from sqlalchemy.orm import Session

from app.core.security import hash_password

from app.db.session import SessionLocal
from app.models.property import Property
from app.models.property_photo import PropertyPhoto
from app.models.user import User



DEMO_OWNER_EMAIL = "owner@immoci.local"
DEMO_OWNER_PHONE = "+22501010101"
DEMO_OWNER_PASSWORD = "demo1234"
DEMO_360_PANORAMA = "https://pannellum.org/images/alma.jpg"

PHOTO_SETS = {
    "studio": [
        "https://images.pexels.com/photos/4392276/pexels-photo-4392276.jpeg?auto=compress&cs=tinysrgb&w=1200",
        "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=1200",
        "https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg?auto=compress&cs=tinysrgb&w=1200",
    ],
    "appartement": [
        "https://images.pexels.com/photos/4392270/pexels-photo-4392270.jpeg?auto=compress&cs=tinysrgb&w=1200",
        "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1200",
        "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1200",
    ],
    "maison": [
        "https://images.pexels.com/photos/4392272/pexels-photo-4392272.jpeg?auto=compress&cs=tinysrgb&w=1200",
        "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1200",
        "https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=1200",
    ],
    "villa": [
        "https://images.pexels.com/photos/4392278/pexels-photo-4392278.jpeg?auto=compress&cs=tinysrgb&w=1200",
        "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1200",
        "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1200",
    ],
}

PROPERTY_DATA = [
    {
        "title": "Appartement meublé résidence calme à Cocody",
        "description": "Résidence sécurisée avec balcon, fibre et accès rapide aux commerces.",
        "property_type": "appartement",
        "price": 320000,
        "price_period": "mois",
        "surface_m2": 82,
        "rooms": 3,
        "bathrooms": 2,
        "address": "Riviera Palmeraie, Cocody",
        "city": "Abidjan",
        "neighborhood": "Cocody",
        "latitude": 5.3694,
        "longitude": -3.9578,
        "is_furnished": True,
        "is_verified_listing": True,
    },
    {
        "title": "Studio moderne proche Plateau",
        "description": "Studio optimisé pour jeunes actifs, climatisé et tout équipé.",
        "property_type": "studio",
        "price": 185000,
        "price_period": "mois",
        "surface_m2": 32,
        "rooms": 1,
        "bathrooms": 1,
        "address": "Biétry, Marcory",
        "city": "Abidjan",
        "neighborhood": "Marcory",
        "latitude": 5.2866,
        "longitude": -3.9684,
        "is_furnished": True,
        "is_verified_listing": True,
    },
    {
        "title": "Villa 5 pièces avec jardin à Angré",
        "description": "Grande maison familiale avec cour, jardin et dépendance.",
        "property_type": "villa",
        "price": 780000,
        "price_period": "mois",
        "surface_m2": 240,
        "rooms": 5,
        "bathrooms": 3,
        "address": "7e tranche, Angré",
        "city": "Abidjan",
        "neighborhood": "Angré",
        "latitude": 5.4113,
        "longitude": -3.9465,
        "is_furnished": False,
        "is_verified_listing": True,
    },
    {
        "title": "Maison basse résidence à Bingerville",
        "description": "Maison confortable dans une zone résidentielle très calme.",
        "property_type": "maison",
        "price": 260000,
        "price_period": "mois",
        "surface_m2": 118,
        "rooms": 4,
        "bathrooms": 2,
        "address": "Quartier résidentiel, Bingerville",
        "city": "Bingerville",
        "neighborhood": "Résidentiel",
        "latitude": 5.3569,
        "longitude": -3.8853,
        "is_furnished": False,
        "is_verified_listing": True,
    },
    {
        "title": "Résidence étudiante à Yopougon",
        "description": "Petite résidence de studios, idéale pour étudiants et jeunes salariés.",
        "property_type": "studio",
        "price": 95000,
        "price_period": "mois",
        "surface_m2": 24,
        "rooms": 1,
        "bathrooms": 1,
        "address": "Sideci, Yopougon",
        "city": "Abidjan",
        "neighborhood": "Yopougon",
        "latitude": 5.3362,
        "longitude": -4.0737,
        "is_furnished": False,
        "is_verified_listing": False,
    },
    {
        "title": "Appartement 4 pièces à Deux Plateaux",
        "description": "Belle résidence avec parking, groupe électrogène et sécurité 24h/24.",
        "property_type": "appartement",
        "price": 410000,
        "price_period": "mois",
        "surface_m2": 110,
        "rooms": 4,
        "bathrooms": 2,
        "address": "Rue des Jardins, Deux Plateaux",
        "city": "Abidjan",
        "neighborhood": "Deux Plateaux",
        "latitude": 5.3718,
        "longitude": -3.9813,
        "is_furnished": True,
        "is_verified_listing": True,
    },
    {
        "title": "Villa duplex avec piscine à Grand-Bassam",
        "description": "Maison de standing avec piscine et terrasse proche de la mer.",
        "property_type": "villa",
        "price": 950000,
        "price_period": "mois",
        "surface_m2": 310,
        "rooms": 6,
        "bathrooms": 4,
        "address": "Zone France, Grand-Bassam",
        "city": "Grand-Bassam",
        "neighborhood": "Zone France",
        "latitude": 5.1961,
        "longitude": -3.7434,
        "is_furnished": True,
        "is_verified_listing": True,
        "tour_360_url": DEMO_360_PANORAMA,
    },
    {
        "title": "Appartement résidence sécurisée à Port-Bouët",
        "description": "Appartement lumineux avec accès rapide à l'aéroport et à la plage.",
        "property_type": "appartement",
        "price": 230000,
        "price_period": "mois",
        "surface_m2": 74,
        "rooms": 3,
        "bathrooms": 2,
        "address": "Vridi cité, Port-Bouët",
        "city": "Abidjan",
        "neighborhood": "Port-Bouët",
        "latitude": 5.2556,
        "longitude": -3.9448,
        "is_furnished": False,
        "is_verified_listing": False,
    },
    {
        "title": "Maison 4 pièces à Yamoussoukro",
        "description": "Logement familial bien ventilé proche des grands axes.",
        "property_type": "maison",
        "price": 175000,
        "price_period": "mois",
        "surface_m2": 125,
        "rooms": 4,
        "bathrooms": 2,
        "address": "Quartier Millionnaire, Yamoussoukro",
        "city": "Yamoussoukro",
        "neighborhood": "Millionnaire",
        "latitude": 6.8276,
        "longitude": -5.2893,
        "is_furnished": False,
        "is_verified_listing": True,
    },
    {
        "title": "Résidence meublée à Bouaké centre",
        "description": "Appartement confortable pour mission courte ou longue durée.",
        "property_type": "appartement",
        "price": 205000,
        "price_period": "mois",
        "surface_m2": 68,
        "rooms": 2,
        "bathrooms": 1,
        "address": "Air France 2, Bouaké",
        "city": "Bouaké",
        "neighborhood": "Air France",
        "latitude": 7.6906,
        "longitude": -5.0304,
        "is_furnished": True,
        "is_verified_listing": True,
    },
    {
        "title": "Villa moderne à San-Pédro",
        "description": "Villa récente avec espace extérieur et garage double.",
        "property_type": "villa",
        "price": 420000,
        "price_period": "mois",
        "surface_m2": 210,
        "rooms": 5,
        "bathrooms": 3,
        "address": "Bardot, San-Pédro",
        "city": "San-Pédro",
        "neighborhood": "Bardot",
        "latitude": 4.7485,
        "longitude": -6.6363,
        "is_furnished": False,
        "is_verified_listing": False,
    },
    {
        "title": "Appartement 3 pièces à Treichville",
        "description": "Idéal pour petite famille, proche transport et marché.",
        "property_type": "appartement",
        "price": 210000,
        "price_period": "mois",
        "surface_m2": 72,
        "rooms": 3,
        "bathrooms": 1,
        "address": "Avenue 8, Treichville",
        "city": "Abidjan",
        "neighborhood": "Treichville",
        "latitude": 5.2901,
        "longitude": -4.0131,
        "is_furnished": False,
        "is_verified_listing": True,
    },
    {
        "title": "Maison de cour rénovée à Abobo",
        "description": "Maison pratique et accessible, idéale pour budget moyen.",
        "property_type": "maison",
        "price": 110000,
        "price_period": "mois",
        "surface_m2": 88,
        "rooms": 3,
        "bathrooms": 1,
        "address": "PK18, Abobo",
        "city": "Abidjan",
        "neighborhood": "Abobo",
        "latitude": 5.4426,
        "longitude": -4.0402,
        "is_furnished": False,
        "is_verified_listing": False,
    },
    {
        "title": "Studio résidence business à Plateau",
        "description": "Studio premium pour cadres, connexion rapide et sécurité.",
        "property_type": "studio",
        "price": 240000,
        "price_period": "mois",
        "surface_m2": 35,
        "rooms": 1,
        "bathrooms": 1,
        "address": "Rue du Commerce, Plateau",
        "city": "Abidjan",
        "neighborhood": "Plateau",
        "latitude": 5.3211,
        "longitude": -4.0163,
        "is_furnished": True,
        "is_verified_listing": True,
    },
    {
        "title": "Villa 6 pièces à Korhogo",
        "description": "Grande propriété avec patio intérieur et dépendance.",
        "property_type": "villa",
        "price": 330000,
        "price_period": "mois",
        "surface_m2": 260,
        "rooms": 6,
        "bathrooms": 3,
        "address": "Quartier Résidentiel, Korhogo",
        "city": "Korhogo",
        "neighborhood": "Résidentiel",
        "latitude": 9.4580,
        "longitude": -5.6296,
        "is_furnished": False,
        "is_verified_listing": True,
    },
    {
        "title": "Appartement standing à Daloa",
        "description": "Résidence récente avec balcon et parking intérieur.",
        "property_type": "appartement",
        "price": 195000,
        "price_period": "mois",
        "surface_m2": 64,
        "rooms": 2,
        "bathrooms": 1,
        "address": "Lobia, Daloa",
        "city": "Daloa",
        "neighborhood": "Lobia",
        "latitude": 6.8911,
        "longitude": -6.4502,
        "is_furnished": True,
        "is_verified_listing": False,
    },
    {
        "title": "Maison familiale à Man",
        "description": "Maison en altitude avec vue dégagée et cour sécurisée.",
        "property_type": "maison",
        "price": 165000,
        "price_period": "mois",
        "surface_m2": 132,
        "rooms": 4,
        "bathrooms": 2,
        "address": "Quartier Libreville, Man",
        "city": "Man",
        "neighborhood": "Libreville",
        "latitude": 7.4125,
        "longitude": -7.5538,
        "is_furnished": False,
        "is_verified_listing": True,
    },
    {
        "title": "Résidence neuve à Songon",
        "description": "Résidence de petits appartements en développement rapide.",
        "property_type": "appartement",
        "price": 145000,
        "price_period": "mois",
        "surface_m2": 58,
        "rooms": 2,
        "bathrooms": 1,
        "address": "Songon Kassemblé",
        "city": "Songon",
        "neighborhood": "Kassemblé",
        "latitude": 5.3205,
        "longitude": -4.2150,
        "is_furnished": False,
        "is_verified_listing": False,
    },
    {
        "title": "Villa duplex à Abengourou",
        "description": "Belle villa avec séjour traversant et annexe indépendante.",
        "property_type": "villa",
        "price": 290000,
        "price_period": "mois",
        "surface_m2": 205,
        "rooms": 5,
        "bathrooms": 3,
        "address": "Quartier Commerce, Abengourou",
        "city": "Abengourou",
        "neighborhood": "Commerce",
        "latitude": 6.7297,
        "longitude": -3.4964,
        "is_furnished": False,
        "is_verified_listing": True,
    },
    {
        "title": "Appartement résidence à Anyama",
        "description": "Appartement simple et propre avec accès facile à l’autoroute.",
        "property_type": "appartement",
        "price": 125000,
        "price_period": "mois",
        "surface_m2": 55,
        "rooms": 2,
        "bathrooms": 1,
        "address": "Belle Ville, Anyama",
        "city": "Anyama",
        "neighborhood": "Belle Ville",
        "latitude": 5.4939,
        "longitude": -4.0511,
        "is_furnished": False,
        "is_verified_listing": False,
    },
    {
        "title": "Studio meublé à Cocody Danga",
        "description": "Studio premium en résidence avec services inclus.",
        "property_type": "studio",
        "price": 220000,
        "price_period": "mois",
        "surface_m2": 29,
        "rooms": 1,
        "bathrooms": 1,
        "address": "Danga, Cocody",
        "city": "Abidjan",
        "neighborhood": "Cocody Danga",
        "latitude": 5.3365,
        "longitude": -3.9939,
        "is_furnished": True,
        "is_verified_listing": True,
    },
    {
        "title": "Maison de ville à Gagnoa",
        "description": "Maison pratique avec cour fermée et pièces spacieuses.",
        "property_type": "maison",
        "price": 140000,
        "price_period": "mois",
        "surface_m2": 96,
        "rooms": 3,
        "bathrooms": 1,
        "address": "Babré, Gagnoa",
        "city": "Gagnoa",
        "neighborhood": "Babré",
        "latitude": 6.1319,
        "longitude": -5.9506,
        "is_furnished": False,
        "is_verified_listing": False,
    },
    {
        "title": "Villa avec terrasse à Bonoua",
        "description": "Villa aérée avec grandes chambres et espace familial.",
        "property_type": "villa",
        "price": 235000,
        "price_period": "mois",
        "surface_m2": 180,
        "rooms": 4,
        "bathrooms": 2,
        "address": "Centre, Bonoua",
        "city": "Bonoua",
        "neighborhood": "Centre",
        "latitude": 5.2697,
        "longitude": -3.5954,
        "is_furnished": False,
        "is_verified_listing": True,
    },
    {
        "title": "Appartement moderne à Koumassi",
        "description": "Résidence familiale proche des axes et commerces quotidiens.",
        "property_type": "appartement",
        "price": 165000,
        "price_period": "mois",
        "surface_m2": 63,
        "rooms": 3,
        "bathrooms": 1,
        "address": "Soweto, Koumassi",
        "city": "Abidjan",
        "neighborhood": "Koumassi",
        "latitude": 5.2897,
        "longitude": -3.9596,
        "is_furnished": False,
        "is_verified_listing": True,
    },
    {
        "title": "Résidence de standing à Zone 4",
        "description": "Appartement haut de gamme avec conciergerie et parking sécurisé.",
        "property_type": "appartement",
        "price": 620000,
        "price_period": "mois",
        "surface_m2": 126,
        "rooms": 4,
        "bathrooms": 3,
        "address": "Zone 4, Marcory",
        "city": "Abidjan",
        "neighborhood": "Zone 4",
        "latitude": 5.2794,
        "longitude": -3.9785,
        "is_furnished": True,
        "is_verified_listing": True,
    },
    {
        "title": "Maison économique à Adjamé",
        "description": "Logement accessible pour petite famille au cœur de la commune.",
        "property_type": "maison",
        "price": 98000,
        "price_period": "mois",
        "surface_m2": 70,
        "rooms": 2,
        "bathrooms": 1,
        "address": "Liberté, Adjamé",
        "city": "Abidjan",
        "neighborhood": "Adjamé",
        "latitude": 5.3652,
        "longitude": -4.0238,
        "is_furnished": False,
        "is_verified_listing": False,
    },
    {
        "title": "Studio résidence à Jacqueville",
        "description": "Petit logement saisonnier proche plage et commerces.",
        "property_type": "studio",
        "price": 75000,
        "price_period": "semaine",
        "surface_m2": 26,
        "rooms": 1,
        "bathrooms": 1,
        "address": "Plage, Jacqueville",
        "city": "Jacqueville",
        "neighborhood": "Plage",
        "latitude": 5.2068,
        "longitude": -4.4142,
        "is_furnished": True,
        "is_verified_listing": False,
    },
    {
        "title": "Villa contemporaine à Assinie",
        "description": "Villa de vacances avec vue lagune et grandes terrasses.",
        "property_type": "villa",
        "price": 1450000,
        "price_period": "semaine",
        "surface_m2": 280,
        "rooms": 5,
        "bathrooms": 4,
        "address": "Assinie Mafia",
        "city": "Assinie",
        "neighborhood": "Mafia",
        "latitude": 5.1328,
        "longitude": -3.2893,
        "is_furnished": True,
        "is_verified_listing": True,
    },
    {
        "title": "Appartement 2 pièces à San Pedro centre",
        "description": "Résidence bien placée pour activité portuaire et services.",
        "property_type": "appartement",
        "price": 135000,
        "price_period": "mois",
        "surface_m2": 51,
        "rooms": 2,
        "bathrooms": 1,
        "address": "Cité, San-Pédro",
        "city": "San-Pédro",
        "neighborhood": "Cité",
        "latitude": 4.7600,
        "longitude": -6.6405,
        "is_furnished": False,
        "is_verified_listing": True,
    },
    {
        "title": "Maison duplex à Aboisso",
        "description": "Duplex spacieux proche centre administratif et écoles.",
        "property_type": "maison",
        "price": 185000,
        "price_period": "mois",
        "surface_m2": 140,
        "rooms": 4,
        "bathrooms": 2,
        "address": "Quartier Commerce, Aboisso",
        "city": "Aboisso",
        "neighborhood": "Commerce",
        "latitude": 5.4678,
        "longitude": -3.2076,
        "is_furnished": False,
        "is_verified_listing": False,
    },
]


def _get_or_create_owner(db: Session) -> User:
    owner = db.query(User).filter(User.email == DEMO_OWNER_EMAIL).first()
    if owner:
        return owner

    owner = User(
        id=uuid.uuid4(),
        email=DEMO_OWNER_EMAIL,
        phone=DEMO_OWNER_PHONE,
        full_name="Yeloo Demo Owner",
        hashed_password=hash_password(DEMO_OWNER_PASSWORD),
        role="proprietaire",
        is_verified=True,
        trust_badge="full",
        created_at=datetime.utcnow(),
    )
    db.add(owner)
    db.commit()
    db.refresh(owner)
    return owner


def _seed_properties(db: Session, owner_id: uuid.UUID) -> int:
    existing_properties = db.query(Property).filter(Property.owner_id == owner_id).all()
    if existing_properties:
        existing_ids = [prop.id for prop in existing_properties]
        db.query(PropertyPhoto).filter(PropertyPhoto.property_id.in_(existing_ids)).delete(
            synchronize_session=False
        )
        db.query(Property).filter(Property.owner_id == owner_id).delete(
            synchronize_session=False
        )
        db.commit()

    created_count = 0
    for index, item in enumerate(PROPERTY_DATA):
        prop = Property(
            id=uuid.uuid4(),
            owner_id=owner_id,
            title=item["title"],
            description=item["description"],
            property_type=item["property_type"],
            price=item["price"],
            price_period=item["price_period"],
            surface_m2=item["surface_m2"],
            rooms=item["rooms"],
            bathrooms=item["bathrooms"],
            address=item["address"],
            city=item["city"],
            neighborhood=item["neighborhood"],
            latitude=item["latitude"],
            longitude=item["longitude"],
            is_furnished=item["is_furnished"],
            tour_360_url=item.get("tour_360_url"),
            status="published",
            is_verified_listing=item["is_verified_listing"],
            views_count=(index + 1) * 7,
            created_at=datetime.utcnow(),
        )
        db.add(prop)
        db.flush()

        photo_urls = PHOTO_SETS.get(item["property_type"], PHOTO_SETS["appartement"])
        for photo_index, photo_url in enumerate(photo_urls):
            db.add(
                PropertyPhoto(
                    id=uuid.uuid4(),
                    property_id=prop.id,
                    url=photo_url,
                    is_primary=photo_index == 0,
                    created_at=datetime.utcnow(),
                )
            )

        created_count += 1

    db.commit()
    return created_count


def run() -> None:
    db = SessionLocal()
    try:
        owner = _get_or_create_owner(db)
        count = _seed_properties(db, owner.id)
        print(f"Seed complete. Inserted {count} properties for {owner.email}.")
    finally:
        db.close()


if __name__ == "__main__":
    run()

